# Generated by Django 3.2.7 on 2021-09-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=100, verbose_name='Title')),
                ('channel_url', models.CharField(max_length=100, verbose_name='Link')),
                ('channel_description', models.TextField(max_length=1000000, verbose_name='Description')),
                ('channel_thumbnail', models.ImageField(upload_to='images/')),
                ('channel_subscribers', models.CharField(max_length=100, verbose_name='Subscribers')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=1000, verbose_name='Title')),
                ('video_url', models.CharField(max_length=100, verbose_name='Link')),
                ('video_description', models.TextField(max_length=1000000, verbose_name='Description')),
                ('video_thumbnail', models.ImageField(upload_to='images/')),
                ('video_views', models.CharField(max_length=100, verbose_name='Views')),
                ('video_date', models.CharField(max_length=20, verbose_name='Date Published')),
                ('video_likes', models.IntegerField(verbose_name='Likes')),
                ('video_dislikes', models.IntegerField(verbose_name='Dislikes')),
                ('video_comments', models.TextField(max_length=1000000, verbose_name='Comments')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.channel')),
            ],
        ),
    ]
