# Generated by Django 3.2.7 on 2021-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_url',
            field=models.URLField(max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=500, verbose_name='Link'),
        ),
    ]
